local X = {}

function X.noremap(mode, lhs, rhs, description, additional_options)
  local options = { noremap = false, silent = true, desc = description }
  if additional_options then
    options = vim.tbl_deep_extend("force", options, additional_options)
  end
  vim.keymap.set(mode, lhs, rhs, options)
end

function X.remap(mode, lhs, rhs, description, additional_options)
  local options = { noremap = true, silent = true, desc = description }
  if additional_options then
    options = vim.tbl_deep_extend("force", options, additional_options)
  end
  vim.keymap.set(mode, lhs, rhs, options)
end

function X.sync_theme_to_tmux()
  local bg_color = string.format("%06x", vim.api.nvim_get_hl(0, { name = "Normal", link = false }).bg)
  local fg_color = string.format("%06x", vim.api.nvim_get_hl(0, { name = "Normal", link = false }).fg)
  local accent_color = string.format("%06x", vim.api.nvim_get_hl(0, { name = "Function", link = false }).fg)
  local filename = vim.fn.expand("~/.config/.tmux-theme")
  local file = io.open(filename, "w")

  if file then
    file:write(string.format([[
#autogenerated by Neovim
set -g status-bg '#%s'
set -g status-fg '#%s'
set -g window-status-current-format "#[fg=#%s,bg=#%s,nobold,noitalics,nounderscore] #[fg=#%s,bg=#%s]#I #[fg=#%s,bg=#%s,nobold,noitalics,nounderscore]| #[fg=#%s,bg=#%s]#W #F #[fg=#%s,bg=#%s,nobold,noitalics,nounderscore]"
]], bg_color, fg_color, bg_color, accent_color, bg_color, accent_color, bg_color, accent_color, bg_color, accent_color,
      accent_color, bg_color))
    file:close()
  end

  vim.fn.system("tmux source-file ~/.config/.tmux-theme")
end

return X
